name: Release to homebrew core

on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        with:
          formula-name: so
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
